### PR TITLE
Add distinct() method

### PR DESCRIPTION
**Pull request by sargunv**
User can do `$db->distinct()->select(...)` to do a distinct selection (add `DISTINCT` to the query).

Used code from the post by @darre4nbrown in issue #113.

This simple to use and a crucial feature for interacting with a database.

### CODE REVIEW

**Comment by JBlond** [comment]
:+1:

**Comment by Sebb767** [comment]
:+1:

You should reset distinct mode after executing a query, however.

**Comment by SyuTingSong** [comment]
I like this feature.
I am thinking about if I provide code `$medoo->distinct()->count('account', 'age')`, what SQL should be generated.

    SELECT DISTINCT COUNT("age") FROM "account"

or

    SELECT COUNT(DISTINCT "age") FROM "account"

**Comment by Sebb767** [comment]
@SyuTingSong it should be ``SELECT DISTINCT...`` since no specific column is given. An overload like ``$medoo->distinct('age')->...`` for specifying a specific the distinct column(s) would be great.

**Comment by SyuTingSong** [comment]
@Sebb767 I merged @sargunster's work to my fork. And I implement auto-reset and `SELECT COUNT(DISTINCT "age") FROM "account"` additionally.

I guess `distinct($column)` is inconsistent with medoo's column function way (e.g. COUNT, MAX, MIN, AVG...). The `distinct` method is more likely a decorator.

You can review my code in commit b7eea7ef6f223da800e52198a1098cdf4f21e036 . Since my fork has merged some others' pull-requests which catfan ignored. I won't create new pull-request here.

Feel free to use and discuss my code.

**Comment by HendrikD** [comment]
:+1:

**Comment by froozeify** [comment]
:thumbsup:

**Comment by JanWerder** [comment]
this would be great

**Comment by tjmckenzie** [comment]
Upvoted.

**Comment by nealoke** [comment]
+1

**Comment by adarshmadrecha** [comment]
@SyuTingSong any plan for implementing this? I am really looking forward to this method.

**Comment by getvivekv** [comment]
Missing this piece

**Comment by sargunv** [comment]
Seems like this project is no longer maintained, closing this old PR to clear my queue.

**Pull request closed without merging**
