### PR TITLE
Change encoding from 'utf8' to 'utf-8'

### PR DESCRIPTION
**Pull request by XipanXiao**
'utf8' is an invalid encoding value and never works.
I followed the documentation but always got garbage Chinese characters until I changed 'utf8' to 'utf-8'.

### CODE REVIEW

**Comment by pwwang** [comment]
You have to use 'utf8' in mysql.
http://dev.mysql.com/doc/refman/5.7/en/charset-unicode.html

**Comment by SyuTingSong** [comment]
Medoo executes `SET NAMES 'utf8'` while initializing mariadb, mysql, pgsql, sybase and mssql.[[code]][1]
The usage of charset in dsn only with oracle.[[code]][2]

And as @pwwang said, 'utf8' is the valid charset name in MySQL.

[1]: https://github.com/catfan/Medoo/blob/master/medoo.php#L134
[2]: https://github.com/catfan/Medoo/blob/master/medoo.php#L110

**Comment by pwwang** [comment]
@SyuTingSong 
You are right, as you can see [code](https://github.com/catfan/Medoo/blob/master/medoo.php#L131), if you don't set `charset` in the constructor, it won't be executed.
So you yourself have to set the right charset for the database you chose.
But as shown in the doc, the example is for mysql, so charset 'utf8' is exactly the right one.

**Comment by SyuTingSong** [comment]
The charset name of UTF-8 is also 'UTF8' or 'utf8' in [PostgreSQL][1], [Sybase][2].

And I just found that [MS SQL Server NOT supports UTF-8 before ver 2012][3]. :o:

[1]: http://www.postgresql.org/docs/current/static/multibyte.html#CHARSET-TABLE
[2]: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc35823.1572/doc/html/san1334282792157.html
[3]: https://stackoverflow.com/questions/12512687/sql-server-utf8-howto

**Pull request closed without merging**
