### PR TITLE
[fix] issue #436

### PR DESCRIPTION
**Pull request by progressify**
for like condition if you use [+~]
you can obtain: col LIKE '%value1%' AND col LIKE '%value2%'

### CODE REVIEW

**Comment by StefansArya** [comment]
Hi buddy, I already fix that problem..
You better check it out: [Link](https://github.com/catfan/Medoo/pull/510)

**Comment by catfan** [comment]
Changed it on v1.2 develop branch. 130e3cd7

It don't use `[+~]` or `[&~]` syntax, because it will conflict the negative condition `[!~]`.

**Comment by StefansArya** [comment]
Good idea, it will cover the NOT LIKE too..
Btw, does it work with:

```
$database->select("account", "id", [
    "name[~]" => [
        "AND" => ["lon", "on"]
        "OR" => ["Foo", "bar"]
]);
```

**Comment by catfan** [comment]
@StefansArya For this case, that's confusing, because we don't know how to connect the `"AND" => xxx` and `"OR" => xxx` on the same array.

To correct this, just write it outside.
```
$database->select("account", "id", [
	"AND" => [
		"content[~]" => ["AND" => ["lon", "on"]],
		"OR" => [
			"content[~]" => ["OR" => ["foo", "bar"]]
		]
	]
]);

// The result
SELECT "id" FROM "account"
WHERE
"content" LIKE '%lon%' AND
"content" LIKE '%on%' AND
(
	"content" LIKE '%foo%' OR
	"content" LIKE '%bar%'
)
```

**Pull request closed without merging**
