### PR TITLE
[feature] Added support for INSERT keywords #329

### PR DESCRIPTION
**Pull request by alihamze**
This commit adds support for keywords in the INSERT function. It checks which keywords are supported based on the `$database_type` before adding them to the query.

For example:

``` php
$last_user_id = $database->insert("account", [
    "user_name" => "foo",
    "email" => "foo@bar.com",
    "age" => 25
], [$database::SQL_NO_CACHE, $database::LOW_PRIORITY]);
```

### CODE REVIEW

**Comment by repat** [comment]
Could you possible to add `INSERT IGNORE` (MySQL/MariaDB) /`ON CONFLICT IGNORE` (sqlite)? Don't know the Oracle equivalent.

btw, what's the `?>` doing there?

**Comment by alihamze** [comment]
@repat I just added it. Oracle also uses [INSERT IGNORE](https://docs.oracle.com/cd/E17952_01/refman-5.1-en/insert.html) like MySQL/MariaDB so I added that too. As for the `?>`, my IDE added a new line after the last line in the file [(see here)](https://robots.thoughtbot.com/no-newline-at-end-of-file).

**Comment by repat** [comment]
@catfan ? :)

**Comment by SyuTingSong** [comment]
good idea

**Comment by ggedde** [comment]
Was hoping this was added. :(
@catfan ?

**Comment by pedrofsantoscom** [comment]
Any ETA for this pull request going to master branch or a new release?

**Comment by catfan** [comment]
This feature is considerable, but will not implement like this way.

Probably will set it as option on initialization. But it's not 100% sure yet from now.

**Pull request closed without merging**
