### PR TITLE
[update] remove unnecessary ELSE statements.

### PR DESCRIPTION
**Pull request by Yousha**

### CODE REVIEW

**Comment by Andrews54757** [comment]
@Yousha Is this needed? What we have works too.

**Comment by Dans24** [comment]
It just save some lines of code

**Comment by Yousha** [comment]
@Andrews54757, @Dans24
Is that illegal to commit some MINOR changes?
I'm are here to contribute(by ANYWAY), not just downloading/using the open source projects like you.

Both stop posting off-topics/spam.

**Comment by Andrews54757** [comment]
@Yousha Lets be civilized. Lets respect each other. Also, I am not just a user, I am a professional developer.


It is not illegal to commit minor changes. However, there are standards.  Your changes might become confusing in the future. 

```php
if ($condition) 
{

    return $a
}
else
{

    return $b
}
```

is better than

```php
if ($condition) 
{

    return $a
}
    return $b
```

catfan knows what she is doing.

**Comment by Yousha** [comment]
> Lets be **civilized**. Lets respect each other.
Says US dude...
First you must drop your Gun

And yea, you are a Professional developer: https://github.com/Andrews54757?tab=repositories

**Comment by Andrews54757** [comment]
@Yousha Look, I am trying to be nice to you. Please dont be rude.

I am trying to contribute and support this repo. I do not need to, I am busy, and I have already created something 5 times better than this. However, I choose to help because I love open-sourced projects. Please respect me, and I will respect you.

**Comment by catfan** [comment]
We always welcome any code contribution or bug fix for the project, even only one character change will possibly have a meaningful improvement.

But for this case, the improvement is insignificant enough and have no visible change. We hope to see better pull request. Thank you :)

And also, stop personal attacks for this technological community. This conversation have to be closed and locked.

**Pull request closed without merging**
