### PR TITLE
[feature] Support aggregate functions in select

### PR DESCRIPTION
**Pull request by mrsoto**
This little change adds support to aggregate functions directly to select.

Example: 
$rows = Flight::db()->select('table',
[ 'column1', 'column2', '[COUNT](cnt)'],
['GROUP'=>['column1','column2']);

### CODE REVIEW

**Comment by mrsoto** [comment]
Fix #191 & #192

**Comment by mynolix** [comment]
I am missing a function to get the columns of a table. Even if the table is empty!
It is possible to add this function?

**Comment by iyaozhen** [comment]
GROUP BY  multiple columns is very useful.

I usually use this way count data.

**Comment by mrsoto** [comment]
Actually, group by only one column is a restriction, not a functionally.

**Comment by catfan** [comment]
This request is closed because it is now able to do that via raw object.

**Pull request closed without merging**
