### PR TITLE
Permit functions in WHERE clause

### PR DESCRIPTION
**Pull request by fly1ted**
This simple solution won't add too much to the code and will allow a powerful functionality of SQL.

### CODE REVIEW

**Comment by SyuTingSong** [comment]
How to use?

**Comment by fly1ted** [comment]
你就像普通的SQL指令使用例如：
$database->select("account", "user_name", [
	"MONTH(reg_date)" => "10"
]);

**Comment by SyuTingSong** [comment]
It's dangerous that generates SQL without column name quote as below:
```sql
SELECT "user_name" FROM "account" WHERE MONTH(reg_date) = '10'
```
Medoo has already provided some useful column functions like count, max, min, sum, avg...

**Comment by fly1ted** [comment]
You're right, what about that?

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.

**Pull request closed without merging**
