### PR TITLE
add additional conditions to join, ref. #167

### PR DESCRIPTION
**Pull request by alpipego**
This change makes it possible to add additional conditions to a join as discussed in #167; 

If the addition is a value with the joined table use the modifier `[$]`:

```
'right_table_column[$]' => value
```

If it is a table relation use it as any other join condition 

```
'left_table_column' => 'right_table_column'
```

### CODE REVIEW

**Comment by alpipego** [comment]
at the moment if the value is a string it has to be quoted before passing it as a parameter.

**Comment by catfan** [comment]
Added this feature.

**Comment by adminko-svk** [comment]
Its also working with the modifier [$] ?

**Comment by TomMasson** [comment]
Hello everyone,
I'm trying since hours to execute this request : 
SELECT "*" FROM "left_table"
LEFT JOIN "right_table"
ON ("left_table.id" = "right_table.id" 
    AND "right_table.number"= 1
    AND "right_table.type"="large");

My problem is that I can't find a way to make work "right_table.column" = 1.
Here is my code, I am on medoo-1.2.1 :
$result = $database->select("left_table", [
            "[>]right_table" => [
                "id" => "id",
                "right_table.number[$]" => 1,
                "right_table.type" => "large"
            ]
        ]);
Looks like "right_table.column[$]" = value does not work because the error message is "Unknown column 'left_table.1' in 'on clause'" (or maybe I am using it wrong? )

Is it possible to do what am I trying ? I really would like to avoid using the query method of medoo.
Thanks by advance !

**Comment by Tagirijus** [comment]
Unfortunately I also cannot figure out how an `AND` can be added into the JOIN-seciont of the SQL query. Using `[$]` as a suffix or using the `quote()` method won't work at all.

Unfortunately the dev also closed all other related issues without commenting it. @catfan : can you please at least answer, **if** this is possible or not? Maybe it's just badly documented in this situation? Maybe it's not possible and won't be in the future? Maybe some of us are just slow in thinking? Please enlighten us at least. (=

Thank you very much (also for this great framework at all, by the way!).

**Comment by catfan** [comment]
@Tagirijus I have added this feature mentioned above so long, but not using `[$]` suffix. 9e4d498

Check out the documentation about multiple condition from Table Joining section.
https://medoo.in/api/select

**Comment by Tagirijus** [comment]
Hey there, thanks for answering. I already tried to understand the commit and I also re-read the join-documentation on the website multiple times. Either it is a bug, or I might misunderstand the whole issue here. The thing is the following:

When I use this array as the join array for the Medoo:
```php
$joiner = [
    '[>]table_to_join' => [
        'column_of_maintable' => 'column_of_jointable',
        'table_to_join.other_column_of_jointable' => 'VALUE'
    ]
];
```

Medoo then translates `'table_to_join.other_column_of_jointable' => 'VALUE'` into this SQL: `'table_to_join.other_column_of_jointable' = 'table_to_join.VALUE'` ... so it does not understand that `'VALUE''` isn't a name of a column, but a specific value, I want to check in an _AND_ statement of the _JOIN_ operation. Like I would do it so:

```SQL
LEFT JOIN
    table_to_join
    ON
        main.column_of_maintable = table_to_join.column_of_jointable
    AND
        table_to_join.other_column_of_jointable = VALUE
```

Hopefully you will be able to understand my problem. Thanks for taking the time! (=

**Comment by catfan** [comment]
@Tagirijus JOIN is describing the relationship between two table. If you want to add a condition to filter the data, put the `table_to_join.other_column_of_jointable = VALUE` to WHERE parameter.

**Comment by catfan** [comment]
@Tagirijus JOIN is describing the relationship between two table. If you want to add a condition to filter the data, put the `table_to_join.other_column_of_jointable = VALUE` to WHERE parameter.

**Comment by Tagirijus** [comment]
Is it normal then that the _AND_ statement, which contains such a condition gives a different SQL-query result than putting this statement in the WHERE section? Because this (during my tests) was the case and that's why I was looking for something like this in Medoo.

**Comment by catfan** [comment]
@Tagirijus 

```SQL
SELECT some_columns
FROM main
LEFT JOIN table_to_join
ON main.column_of_maintable = table_to_join.column_of_jointable
WHERE table_to_join.other_column_of_jointable = VALUE
```

**Comment by Tagirijus** [comment]
Ok, I think I have to come up with an example. To keep things as simple as possible let's say I have three tables:

Main "main":
- Columns: ID, Title

Item "item":
- Columns: ID, Name

Connection-Table "connector":
- Columns: mainID, itemID, additional


Let's say I have some items in all tables. And I also have _items_ connected to the _main_ table with the _connector_ table, while also having an _additional_ feature stored in the _additional_ column of the _connector_ table.

Now I want to search and count all connections of _main_ entries to the items, **but only which have the additional "abc"**, otherwise the count should be `NULL`. I'd do it this way in SQL:


```sql
CREATE TABLE main
(
    ID         int(11) UNSIGNED NOT NULL,
    Title      varchar(255)
);

CREATE TABLE item
(
    ID         int(11) UNSIGNED NOT NULL,
    Name       varchar(255)
);

CREATE TABLE connector
(
    mainID     int(11) UNSIGNED NULL,
    itemID     int(11) UNSIGNED NULL,
    additional varchar(255)
);


INSERT INTO main (ID, Title) VALUES (1, 'main 1');
INSERT INTO main (ID, Title) VALUES (2, 'main 2');
INSERT INTO main (ID, Title) VALUES (3, 'main 3');

INSERT INTO item (ID, Name) VALUES (1, 'item 1');
INSERT INTO item (ID, Name) VALUES (2, 'item 2');
INSERT INTO item (ID, Name) VALUES (3, 'item 3');


INSERT INTO connector (mainID, itemID, additional) VALUES (1, 1, 'abc');
INSERT INTO connector (mainID, itemID, additional) VALUES (1, 2, 'abc');
INSERT INTO connector (mainID, itemID, additional) VALUES (1, 3, NULL);

INSERT INTO connector (mainID, itemID, additional) VALUES (2, 2, NULL);
INSERT INTO connector (mainID, itemID, additional) VALUES (2, 3, 'something else');

INSERT INTO connector (mainID, itemID, additional) VALUES (3, 1, NULL);
INSERT INTO connector (mainID, itemID, additional) VALUES (3, 2, NULL);
INSERT INTO connector (mainID, itemID, additional) VALUES (3, 3, 'abc');


SELECT
	main.ID as mainID,
	NULLIF(COUNT(itemID), 0) AS Count
FROM
	main
LEFT JOIN
	connector
	ON
		main.ID = connector.mainID
	AND
		connector.additional = 'abc'
GROUP BY main.ID
```

Results:

| mainID | Count |
--- | ---
| 1 | 2 |
| 2 |  |
| 3 | 1 |


With your approach the result will miss **mainID == 2**, like so:


```sql
SELECT
	main.ID as mainID,
	NULLIF(COUNT(itemID), 0) AS Count
FROM
	main
LEFT JOIN
	connector
	ON
		main.ID = connector.mainID
WHERE
	connector.additional = 'abc'
GROUP BY main.ID
```

Results:

| mainID | Count |
--- | ---
| 1 | 2 |
| 3 | 1 |


Or am I still missing something here?

By the way: I did the test on the fly on https://sqltest.net/


Thanks for your help, catfan. (=

**Comment by catfan** [comment]
@Tagirijus Thanks for the detailed explanation. That's uncommon usage. I make a change for this feature. 572d3dc

Can be possible to make this condition like this:
```php

'[>]table_to_join' => [
    'column_of_maintable' => 'column_of_jointable',
    'AND' => [
        'table_to_join.other_column_of_jointable' => 'VALUE'
    ]
]
```

```SQL
LEFT JOIN `table_to_join`
ON `main`.`column_of_maintable` = `table_to_join`.`column_of_jointable` AND
`table_to_join`.`other_column_of_jointable` = 'VALUE'
```

Will have more tests later and will be on next v2.0 version.

**Pull request closed without merging**
